package appconfig

const (
	API_VERSION_1_0_0 = "1.0.0"
	API_VERSION_2_0_0 = "2.0.0"

	DRIVER_LIST_ALL_CONFIG_KEY                    = "DRIVER_LIST_ALL_CONFIG_KEY"
	PASSENGER_LIST_ALL_CONFIG_KEY                 = "PASSENGER_LIST_ALL_CONFIG_KEY"
	SERVICEGROUP_LIST_ALL_CONFIG_KEY              = "SERVICEGROUP_LIST_ALL_CONFIG_KEY"
	NONE_AUTHORIZED_CONFIG_KEY                    = "NOT_AUTHORIZED_CONFIG_KEY"
	DRIVER_NONE_AUTHORIZED_LIST_ALL_CONFIG_KEY    = "DRIVER_NONE_AUTHORIZED_LIST_ALL_CONFIG_KEY"
	PASSENGER_NONE_AUTHORIZED_LIST_ALL_CONFIG_KEY = "PASSENGER_NONE_AUTHORIZED_LIST_ALL_CONFIG_KEY"
	MASTER_CONFIG_KEY                             = "MASTER_CONFIG_KEY"
	MASTER_LIST_ALL_CONFIG_KEY                    = "MASTER_ALL"
)
